apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: 3-tier-app-eks
  labels:
    service: database
spec:
  type: ExternalName
  externalName: vikas-postgres.cjqikg0oeg74.sa-east-1.rds.amazonaws.com
  ports:
  - port: 5432
  # postgres-db.devopsdozo.svc.cluster.local  
